export const GET_ALL_CARDS = '[CARDS] GET_ALL_CARDS';
export const GET_ALL_MECHANICS = '[CARDS] GET_ALL_MECHANICS';
export const START_CARDS_LODAING = '[CARDS] START_CARDS_LOADING';
export const FAILED_CARDS_LOADING = '[CARDS] FAILED_CARDS_LOADING';
